
title: "Abinash Chettri"
description: "Anime • Engineering • Student Life"
theme: jekyll-theme-slate
author: Abinash Chettri

url: "https://abinashhchettri.github.io"

header_pages:
  - about.md
  - projects.md
